config/routes.rb
Rails.application.routes.draw do
  devise_for :specialists
  root to: 'pages#home'

  devise_for :patients

  resources :episodes do
    collection do
      get :chrono
    end

    resources :appointments, only: [:new, :create, :edit, :update] do
      resources :documents, only: [:new, :create]
    end
    resources :notes, only: [:new, :create, :edit, :update] do
      resources :documents, only: [:new, :create]
    end

    resources :caregivers, only: [:new, :create]

  end

  resources :events, only: [:edit, :update, :show, :destroy]

  resources :documents, only: [:edit, :update, :destroy]

  resource :profile, only: [:show, :edit, :update]

  namespace :medical_details do
    root to: 'dashboard#show'

    resources :measures, only: [:new, :create, :edit, :update, :destroy]
    resources :vaccinations, only: [:new, :create, :edit, :update, :destroy]
    resources :allergies, only: [:new, :create, :edit, :update, :destroy]
    resources :antecedents, only: [:new, :create, :edit, :update, :destroy]
  end


  resources :caregivers, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
   resources :episodes do
     resources :invitations, only: [:create]
    end
  end

end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :patient
  has_many :events, dependent: :destroy
  validates :name, presence: true
  mount_uploader :icon, PhotoUploader
  has_many :invitations

  # pg_search_scope :global_search,
  #  # against: [ :title, :syllabus ],
  #  associated_against: {
  #    events: [ :description, :last_name ]
  #  }

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def show
    @episode = Episode.find_by_id(params[:id])
    @events  = @episode.events

    if params[:search]
      if params[:search] == "rendez-vous"
        params[:search] = "appointment"
      end
      @events = @events.search(params[:search]).reorder("")
    end

    if params[:category]
      @events = @events.
        joins('INNER JOIN documents ON documents.event_id = events.id'). # We have to force the table alias thanks to pg_search
        where(documents: { category: params[:category] })
    end

    if @events == []
      message = "Vous ne possédez pas de #{params[:category] || 'événement'} pour cet épisode"

      if params[:search]
        message += " avec le mot #{params[:search]}"
      end

      flash[:notice] = message
      return redirect_to episode_path(@episode)
    end


    @events = @events.order(date: :desc)

    @appointment  = Event.new(category: "appointment")
    @note         = Event.new(category: "note")
    @episode_caregivers   = current_patient.caregivers.for_episode(@episode.id)
    @caregivers   = current_patient.caregivers
    @document     = Document.new
    @caregiver    = Caregiver.new
  end

  # /episodes/191?search=Greene&category=radio
  # /episodes/191?category=radio

  # episode_path(@episode, search: "Greene", category: "radio")
  # episode_path(@episode, category: "radio")

  def index
    # better use of associations
    # Order episodes / date events la plus récente
    # Pas très efficace

    @episodes = current_patient.episodes.joins(:events).order("events.date desc").to_a.uniq
    if params[:name]
      if params[:name] != ''
      @episodes  = @current_patient.episodes.where("name ILIKE ?", "%#{params[:name]}%")
      else
        @episodes = current_patient.episodes.joins(:events).order("events.updated_at desc").to_a.uniq
      end
    end
    @episode = Episode.new
    @caregivers = current_patient.caregivers
    @caregiver = Caregiver.new
  end

  def chrono
    @events = Event.
      joins(:episode).
      where(episodes: { patient_id: current_patient.id }).
      order(date: :desc)
    @episodes     = @episodes = current_patient.episodes.joins(:events).order("events.updated_at desc").to_a.uniq
    @appointment  = Event.new(category: "appointment")
    @note         = Event.new(category: "note")
    @caregivers   = current_patient.caregivers
    @document     = Document.new
  end

  def new
    @episode = Episode.new
  end

  def create
    @episode        = Episode.new(episode_params)
    @episode.patient = current_patient
    initial_event   = Event.new(category: "note", description: "Création de l'épisode #{@episode.name}", date: DateTime.now)
    @episode.events << initial_event
    if Picto.where("name ILIKE?", "%#{@episode.name}%") != []
      name = Picto.where("name ILIKE?", "%#{@episode.name}%").first.name
      @episode.icon = File.open(Rails.root.join("app/assets/images/icons/#{name}.png"))
    else
      @episode.icon = File.open(Rails.root.join("app/assets/images/icons/notepad.png"))
    end

    if @episode.save
      redirect_to episodes_path
    else
      render :new
    end
  end

  private

  def episode_params
    params.require(:episode).permit(:name, :description)
  end

end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def document_path(episode, event)
    if event.category == "appointment"
      episode_appointment_documents_path(episode, event)
    else
      episode_note_documents_path(episode, event)
    end
  end
end

app/views/episodes/_form_new_episode.html.erb
<%= simple_form_for @episode do |f| %>
  <%= f.input :name, { label: 'Name', class: "form-text" } %>
  <%= f.input :description, class: "form-text" %>

  <div class="form_new_validation">
    <%= f.submit "Ajouter un épisode" , class: "btn-dark-blue"%>
  </div>
<% end %>

app/views/episodes/index.html.erb
<div class="main-container">

  <div class="index_episode-sidebar">
    <h1>Bonjour <% if !current_patient.firstname.nil?%>  <%= current_patient.firstname.capitalize %>  <% end %></h1>

    <div class="separator"></div>


    <div class="sidebarbtn">
      <div class="btn-dark-blue" data-toggle="modal" data-target="#addEpisode"> Ajouter un épisode
      </div>
    </div>

    <h2>Mon équipe soignante</h2>

                  <%@caregivers.each do |caregiver| %>
                      <%= link_to caregiver_path(caregiver) do %>
                      <div class="episode-sidebar-caregiver">
                        <div class="episode-sidebar-caregiver-avatar">
                          <%= cl_image_tag caregiver.photo, :height=> 35 %>
                        </div>
                        <div class="episode-sidebar-caregiver-fullname">
                          <%= caregiver.firstname %> <%= caregiver.lastname %>
                        </div>
                        <div class="episode-sidebar-cargiver-speciality">
                          <%= caregiver.speciality %>
                        </div>
                      </div>
                      <% end %>
                      <% end %>




    <div class="btn-level2" data-toggle="modal" data-target="#addCaregiver">> Ajouter un soignant
    </div>
  </div>


<div class="episodes-index-container">
  <div class="episodes-head">
    <div class="episodes-title">
      Mes épisodes
    </div>
<div class="chrono">
      <%#= link_to chrono_episodes_path do%>

        <%# end %>
      </div>
  </div>

  <div class="rowbtn">

    <div class="search">
      <%= form_tag(episodes_path, method: :get) do %>
      <%= text_field_tag :name, params[:name], class: 'search-box', placeholder: "Rechercher un dossier"  %>
      <% end %>
    </div>

    <div class="btn-dark-blue visible-xs" data-toggle="modal" data-target="#addEpisode" style="width: 200px; margin-top: 10px"> Ajouter un épisode
    </div>

<!-- modal add episode -->
    <div class="modal fade" id="addEpisode" tabindex="-1" role="dialog" aria-labelledby=addEpisodeLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <%= simple_form_for @episode do |f| %>
        <div class="modal-content">
          <div class="" id="modal-add-note-header">
            <h4 class="modal-title modal-episode" id="addEpisodeLabel"> <p>Ajouter un épisode medical</p></h4>
          </div>
          <div class="modal-body">
              <%= f.input :name, class: "form-text" %>
              <%= f.input :description, class: "form-text" %>
          </div>

          <div class="modal-footer">
            <%= f.submit "Ajouter un épisode" , class: "btn-dark-blue"%>
          </div>

        </div>
        <% end %>
      </div>
    </div>
<!-- modal add caregiver -->
    <div class="modal fade" id="addCaregiver" tabindex="-1" role="dialog" aria-labelledby=addCaregiverLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header" id="modal-add-appointment-header">
            <h4 class="modal-title modal-title-form modal-add-caregiver" id="addCaregiverLabel"> <p>Ajouter un soignant</p></h4>

        </div>
        <div class="modal-body">
          <%= render "caregivers/form_caregiver" %>
        </div>
       <!--  <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        </div> -->
      </div>
    </div>
  </div>


</div>

<div class="episodes">
  <div class="row">
    <% @episodes.each do |episode| %>
    <!-- episode card beginning -->

    <div class="col-xs-12 col-md-3">
      <div class="card-episode">
        <%= link_to episode_path(episode) do %>
        <div class="card-episode-upbox">
          <div class="episode-name">
            <%= episode.name.capitalize %>
            <div class="icon">
              <%= cl_image_tag episode.icon, :height=> 35 %>
            </div>
          </div>
        </div>
        <div class="card-episode-downbox">
          <div class="episode-date">
            Mis à jour le <%= episode.events.order(date: :desc).first.date.strftime("%d-%m-%Y") %>
          </div>
          <div class="episode-button">
            <div>

              <div class="blue-btn decoration-btn"> Voir l'épisode </div>

            </div>
          </div>

        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>
</div>
</div>

app/views/episodes/new.html.erb
 <!-- <div class="container"> -->
  <div class="row_new_episode">
    <div class="col-xs-12">
      <%= render ("form_new_episode.html.erb") %>
    </div>
  </div>
<!-- </div> -->