config/routes.rb
Rails.application.routes.draw do
  devise_for :specialists
  root to: 'pages#home'

  devise_for :patients

  resources :episodes do
    collection do
      get :chrono
    end

    resources :appointments, only: [:new, :create, :edit, :update] do
      resources :documents, only: [:new, :create]
    end
    resources :notes, only: [:new, :create, :edit, :update] do
      resources :documents, only: [:new, :create]
    end

    resources :caregivers, only: [:new, :create]

  end

  resources :events, only: [:edit, :update, :show, :destroy]

  resources :documents, only: [:edit, :update, :destroy]

  resource :profile, only: [:show, :edit, :update]

  namespace :medical_details do
    root to: 'dashboard#show'

    resources :measures, only: [:new, :create, :edit, :update, :destroy]
    resources :vaccinations, only: [:new, :create, :edit, :update, :destroy]
    resources :allergies, only: [:new, :create, :edit, :update, :destroy]
    resources :antecedents, only: [:new, :create, :edit, :update, :destroy]
  end


  resources :caregivers, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
   resources :episodes do
     resources :invitations, only: [:create]
    end
  end

end

app/models/allergie.rb
class Allergie < ApplicationRecord
  belongs_to :patient
  validates :name, presence: true
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :patient
  validates :name, presence: true
end

app/models/antecedent.rb
class Antecedent < ApplicationRecord
  belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  has_many :events
  has_many :episodes, through: :events

  belongs_to :patient
  validates :lastname, presence: true
  validates :speciality, presence: true
  mount_uploader :photo, PhotoUploader

  scope :for_episode, ->(episode_id) { joins(:episodes).where("episodes.id = ?", episode_id).distinct }
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :event
  validates :name, presence: true
  validates :category, presence: true
  mount_uploader :document, PhotoUploader
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :patient
  has_many :events, dependent: :destroy
  validates :name, presence: true
  mount_uploader :icon, PhotoUploader
  has_many :invitations

  # pg_search_scope :global_search,
  #  # against: [ :title, :syllabus ],
  #  associated_against: {
  #    events: [ :description, :last_name ]
  #  }

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :documents, dependent: :destroy
  belongs_to :episode
  belongs_to :caregiver, optional: true
  mount_uploader :icon, PhotoUploader


  include PgSearch

  pg_search_scope :search,
    against: [ :description, :category],
    associated_against: {
      documents: [ :name, :category ],
      caregiver: [:firstname, :lastname, :speciality]
    }

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :episode
  belongs_to :caregiver
  belongs_to :specialist, optional: true
  validates :invitation_token, uniqueness: true, allow_nil: true
end

app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :patient
  validates :name, presence: true
  validates :value, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :episodes, dependent: :destroy
  has_many :events, through: :episodes
  has_many :caregivers, dependent: :destroy
  has_many :measures, dependent: :destroy
  has_many :vaccinations, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_many :antecedents, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/picto.rb
class Picto < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/specialist.rb
class Specialist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :invitations
  has_many :episodes, through: :invitations
  has_many :patients, -> { distinct }, through: :episodes
  # et penser a mettre un  -> { distinct }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  belongs_to :patient
  validates :vaccin, presence: true
end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController

  def create
    @caregiver = Caregiver.new(caregiver_params)
    @caregiver.patient = current_patient

    if @caregiver.save
      if @caregiver.photo.url.nil?
        @caregiver.photo = File.open(Rails.root.join("app/assets/images/doctor-green.png"))
        @caregiver.save
      end
      if caregiver_hidden_params[:from] == "index"
        redirect_to episodes_path
      else
        event = Event.new(category: "appointment", description: "Ajout de #{@caregiver.firstname} #{@caregiver.lastname}, #{@caregiver.speciality}", date: Date.today)
        episode = Episode.find(params[:episode_id])
        event.episode = episode
        event.caregiver = @caregiver
        event.save
        redirect_to episode_path(episode)
      end
    else
      render :new
    end
  end

  def show
    @caregiver = current_patient.caregivers.find(params[:id])

    @episodes = current_patient.episodes.joins(:events).where(events: { caregiver_id: @caregiver.id }).uniq
    @other_episodes = current_patient.episodes.where.not(id: @episodes.map(&:id))

    @invitation = Invitation.new
  end

  private

  def caregiver_params
    params.require(:caregiver).permit(:firstname, :lastname, :address, :mail, :phone_number, :speciality, :photo)
  end

  def caregiver_hidden_params
    params.require(:caregiver).permit(:from)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController



def new
end

def create


end

private

def event_params
  end


end



  # category: "consultation",
  #   description: " Il a remarqué une epine calcanéenne sous mon pied gauche. A confirmer avec le docteur Greene",
  #   episode: Episode.first,
  #   date: "2017-02-01",
  #   caregiver: Caregiver.all[2]

app/controllers/notes_controller.rb
class NotesController < ApplicationController


  def new
    @episode = Episode.find(params[:episode_id])
    @note = Event.new(category: "note")

  end

  def create
    @episode = Episode.find(params[:episode_id])
    @note = Event.new(episode_id: @episode.id ,category:"note", description: note_params[:description], date: DateTime.now)
    if @note.save
      redirect_to episode_path(@episode)
    else

    end
  end

  def edit
     @note = Event.find(params[:id])
  end

  def update
    @note = Event.find(params[:id])
    @note.update(note_params)

    if @note.save
       redirect_to episode_path(@note.episode_id)
    else
    end
  end


private

  def note_params
      params.require(:event).permit(:description )
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_patient!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def document_path(episode, event)
    if event.category == "appointment"
      episode_appointment_documents_path(episode, event)
    else
      episode_note_documents_path(episode, event)
    end
  end
end

app/helpers/meta_tags_helper.rb
 module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end

  def meta_product_name
    content_for?(:meta_product_name) ? content_for(:meta_product_name) : DEFAULT_META["meta_product_name"]
  end
end

app/views/caregivers/_form_caregiver.html.erb
<%= simple_form_for @caregiver, url: caregivers_path, method: :post do |form| %>
  <%= form.input :firstname, :label => "Prénom" %>
  <%= form.input :lastname, :label => "Nom" %>
  <%= form.input :address, :label => "Adresse" %>
  <%= form.input :mail, :label => "Mail" %>
  <%= form.input :phone_number, :label => "Numéro de téléphone" %>
  <%= form.input :speciality, :label => "Profession" %>
  <%= form.input :photo, label: "Ajoutez la photo" %>
  <%= form.hidden_field :from, value: "index" %>
  <%= form.submit "Ajouter un docteur", class: "btn-cool-green"  %>
<% end %>

app/views/caregivers/_form_episode_caregiver.html.erb
<%= simple_form_for [episode, @caregiver], url: episode_caregivers_path(episode), method: :post do |form| %>
  <%= form.input :firstname, :label => "Prénom" %>
  <%= form.input :lastname, :label => "Nom" %>
  <%= form.input :address, :label => "Adresse" %>
  <%= form.input :mail, :label => "Mail" %>
  <%= form.input :phone_number, :label => "Numéro de téléphone" %>
  <%= form.input :speciality, :label => "Profession" %>
  <%= form.input :photo, label: "Ajoutez la photo" %>
  <%= form.hidden_field :from, value: "show" %>
  <%= form.submit "Ajouter un docteur", class: "btn-cool-green"  %>
<% end %>

app/views/caregivers/new.html.erb
<div class="container">
  <%= render "form_caregiver" %>
</div>

app/views/caregivers/new_episode.html.erb
<div class="container">
  <%= render "form_episode_caregiver" %>
</div>

app/views/caregivers/show.html.erb
<div class="main-container">

  <div class="index_episode-sidebar">
    <div class="caregiver-head">
      <h1> <%= @caregiver.firstname %> <%= @caregiver.lastname %></h1>
    </div>
    <div class="separator"></div>
    <div class="caregiver-head">
      <h2><%= @caregiver.speciality %></h2>
    </div>
    <div class="photo-caregiver">
      <%= cl_image_tag @caregiver.photo, :height=> 35 %>
    </div>
    <div class="caregiver-details">
        <p><%= @caregiver.address %></p>
        <p><%= @caregiver.mail %></p>
        <p><%= @caregiver.phone_number %></p>

    </div>
  </div>

  <div class="episodes-index-container">
    <div class="episodes-head">
      <div class="episodes-title">
        <div>
          <h3 span style = "color: #21314e"><i class="fa fa-share-alt" aria-hidden="true"></i>   Partager vos épisodes </h3>


        </div>
      </div>
    </div>

    <div class="rowbtn">

    </div>

    <% if @episodes.count > 0  %>
    <div class="episodes">
      <h3 span style = "color: #21314e">Episodes associés</h3>
      <div class="row">
        <% @episodes.each do |episode| %>
        <!-- episode card beginning -->

          <div class="col-xs-12 col-sm-3 col-md-3">
            <div class="card-episode">
              <%= link_to caregiver_episode_invitations_path(@caregiver, episode), {:method => :post } do %>
                <div class="card-episode-upbox">
                  <div class="episode-name">
                    <%= episode.name.capitalize %>
                      <div class="icon">
                        <%= cl_image_tag episode.icon, :height=> 35 %>
                      </div>
                  </div>
                </div>
                <div class="card-episode-downbox">
                  <div class="episode-date">
                    <% if episode.events !=[] %>
                    Mis à jour le <%= episode.events.order(updated_at: :desc).first.updated_at.strftime("%d-%m-%Y") %>
                    <% end %>
                  </div>
                  <div class="episode-button">

                    <div class=" decoration-btn">
                       <% if episode.invitations.where("invitations.caregiver_id = ?", @caregiver.id) != []  %>
                          <% if episode.invitations.where("invitations.caregiver_id = ?", @caregiver.id).first.status == "Pending"%>
                              En attente
                          <% end %>
                        <% else %>
                          Partager
                        <% end %>
                    </div>
                  </div>

                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>

      <div class="episodes">
      <h3 span style = "color: #21314e" >Episodes non associés</h3>
      <div class="row">
        <% @other_episodes.each do |episode| %>
        <!-- episode card beginning -->

          <div class="col-xs-12 col-sm-3 col-md-3">
            <div class="card-episode">
              <%= link_to caregiver_episode_invitations_path(@caregiver, episode), {:method => :post } do %>
                <div class="card-episode-upbox">
                  <div class="episode-name">
                    <%= episode.name.capitalize %>
                      <div class="icon">
                        <%= cl_image_tag episode.icon, :height=> 35 %>
                      </div>
                  </div>
                </div>
                <div class="card-episode-downbox">
                  <div class="episode-date">
                    <% if episode.events !=[] %>
                    Mis à jour le <%= episode.events.order(updated_at: :desc).first.updated_at.strftime("%d-%m-%Y") %>
                    <% end %>
                  </div>
                  <div class="episode-button">

                    <div class=" decoration-btn">
                       <% if episode.invitations.where("invitations.caregiver_id = ?", @caregiver.id) != []  %>
                          <% if episode.invitations.where("invitations.caregiver_id = ?", @caregiver.id).first.status == "Pending"%>
                              En attente
                          <% end %>
                        <% else %>
                          Partager
                        <% end %>
                    </div>
                  </div>

                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>