config/routes.rb
Rails.application.routes.draw do
  devise_for :specialists
  root to: 'pages#home'

  devise_for :patients

  resources :episodes do
    collection do
      get :chrono
    end

    resources :appointments, only: [:new, :create, :edit, :update] do
      resources :documents, only: [:new, :create]
    end
    resources :notes, only: [:new, :create, :edit, :update] do
      resources :documents, only: [:new, :create]
    end

    resources :caregivers, only: [:new, :create]

  end

  resources :events, only: [:edit, :update, :show, :destroy]

  resources :documents, only: [:edit, :update, :destroy]

  resource :profile, only: [:show, :edit, :update]

  namespace :medical_details do
    root to: 'dashboard#show'

    resources :measures, only: [:new, :create, :edit, :update, :destroy]
    resources :vaccinations, only: [:new, :create, :edit, :update, :destroy]
    resources :allergies, only: [:new, :create, :edit, :update, :destroy]
    resources :antecedents, only: [:new, :create, :edit, :update, :destroy]
  end


  resources :caregivers, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
   resources :episodes do
     resources :invitations, only: [:create]
    end
  end

end

app/models/allergie.rb
class Allergie < ApplicationRecord
  belongs_to :patient
  validates :name, presence: true
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :patient
  validates :name, presence: true
end

app/models/antecedent.rb
class Antecedent < ApplicationRecord
  belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  has_many :events
  has_many :episodes, through: :events

  belongs_to :patient
  validates :lastname, presence: true
  validates :speciality, presence: true
  mount_uploader :photo, PhotoUploader

  scope :for_episode, ->(episode_id) { joins(:episodes).where("episodes.id = ?", episode_id).distinct }
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :event
  validates :name, presence: true
  validates :category, presence: true
  mount_uploader :document, PhotoUploader
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :patient
  has_many :events, dependent: :destroy
  validates :name, presence: true
  mount_uploader :icon, PhotoUploader
  has_many :invitations

  # pg_search_scope :global_search,
  #  # against: [ :title, :syllabus ],
  #  associated_against: {
  #    events: [ :description, :last_name ]
  #  }

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :documents, dependent: :destroy
  belongs_to :episode
  belongs_to :caregiver, optional: true
  mount_uploader :icon, PhotoUploader


  include PgSearch

  pg_search_scope :search,
    against: [ :description, :category],
    associated_against: {
      documents: [ :name, :category ],
      caregiver: [:firstname, :lastname, :speciality]
    }

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :episode
  belongs_to :caregiver
  belongs_to :specialist, optional: true
  validates :invitation_token, uniqueness: true, allow_nil: true
end

app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :patient
  validates :name, presence: true
  validates :value, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :episodes, dependent: :destroy
  has_many :events, through: :episodes
  has_many :caregivers, dependent: :destroy
  has_many :measures, dependent: :destroy
  has_many :vaccinations, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_many :antecedents, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/picto.rb
class Picto < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/specialist.rb
class Specialist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :invitations
  has_many :episodes, through: :invitations
  has_many :patients, -> { distinct }, through: :episodes
  # et penser a mettre un  -> { distinct }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  belongs_to :patient
  validates :vaccin, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController


  def new
    @episode = Episode.find(params[:episode_id])
    @note = Event.new(category: "note")

  end

  def create
    @episode = Episode.find(params[:episode_id])
    @note = Event.new(episode_id: @episode.id ,category:"note", description: note_params[:description], date: DateTime.now)
    if @note.save
      redirect_to episode_path(@episode)
    else

    end
  end

  def edit
     @note = Event.find(params[:id])
  end

  def update
    @note = Event.find(params[:id])
    @note.update(note_params)

    if @note.save
       redirect_to episode_path(@note.episode_id)
    else
    end
  end


private

  def note_params
      params.require(:event).permit(:description )
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_patient!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def document_path(episode, event)
    if event.category == "appointment"
      episode_appointment_documents_path(episode, event)
    else
      episode_note_documents_path(episode, event)
    end
  end
end

app/helpers/meta_tags_helper.rb
 module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end

  def meta_product_name
    content_for?(:meta_product_name) ? content_for(:meta_product_name) : DEFAULT_META["meta_product_name"]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- meta tags -->
    <meta name="title" content="<%= meta_title %>" />
    <meta name="ProductName" content="<%= meta_product_name %>" />
    <meta name="ProductTagline" content="<%= meta_description %>" />
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner " style="background-image: linear-gradient(-225deg, rgba(192,192,170,0.6) 0%, rgba(126, 183, 246, 0.6) 50%), url('<%= image_path("bg.jpg")%>');">

  <div class="banner-content">

    <h1><span style = "color: #00ce79">K</span>enko</h1>
    <span class="wrap">
      <h2 href="" class="typewrite" data-period="2000000000" data-type='[ "Votre nouveau carnet médical nomade"]'>
      </span>
    </h2>

    <%= link_to "Créez votre Kenko", episodes_path, class: "btn btn-home" %>
  </div>
</div>




<script>
  var TxtType = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = '';
        this.tick();
        this.isDeleting = false;
    };

    TxtType.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
        this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
        this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

        var that = this;
        var delta = 200 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
        delta = this.period;
        this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
        this.isDeleting = false;
        this.loopNum++;
        delta = 500;
        }

        setTimeout(function() {
        that.tick();
        }, delta);
    };

    window.onload = function() {
        var elements = document.getElementsByClassName('typewrite');
        for (var i=0; i<elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-type');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
              new TxtType(elements[i], JSON.parse(toRotate), period);
            }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
        document.body.appendChild(css);
    };


</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->


  <% if patient_signed_in? %>
    <%= link_to episodes_path, class: "navbar-wagon-brand" do %>
      <span style = "color: #00ce79">K</span>enko
    <% end %>

    <% else %>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <span style = "color: #00ce79">K</span>enko
      <% end %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if patient_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Mes épisodes", episodes_path, class: "navbar-wagon-item navbar-wagon-link" %>




      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_patient.photo, width: 30, height: 30, :radius=>"max", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
<!--             <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%#= t(".profile", default: "Profile") %>
              <%# end %>
            </li>
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Settings") %>
              <%# end %>
            </li> -->
            <li>
              <%= link_to destroy_patient_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Me déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Me connecter"), episodes_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Mes épisodes", episodes_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Mon profil", profile_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

      </ul>
    </div>
  </div>
</div>